# Generated by Django 4.1.7 on 2023-03-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='id',
        ),
        migrations.AddField(
            model_name='projects',
            name='ids',
            field=models.IntegerField(default=1, help_text='项目主键', primary_key=True, serialize=False, verbose_name='项目主键'),
            preserve_default=False,
        ),
    ]
