# Generated by Django 4.1.7 on 2023-03-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_projects_ids_projects_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='id',
            field=models.AutoField(help_text='项目主键', primary_key=True, serialize=False, verbose_name='项目主键'),
        ),
    ]
